action_app_name=${do_name}_${app_name}
things_list=("branch-load-misses" "branch-loads" "dTLB-load-misses" "dTLB-loads" "iTLB-load-misses" "iTLB-loads" "L1-dcache-load-misses" "L1-dcache-loads" "L1-icache-load-misses" "L1-icache-loads" "branch-misses" "bus-cycles" "cache-misses" "cache-references" "stalled-cycles-backend" "stalled-cycles-frontend" "raw-ase-spec" "raw-br-immed-retired" "raw-br-immed-spec" "raw-br-indirect-spec" "raw-br-pred" "raw-br-mis-pred" "raw-br-mis-pred-retired" "raw-br-retired" "raw-br-return-retired" "raw-br-return-spec" "raw-bus-access" "raw-bus-access-rd" "raw-bus-access-wr" "raw-bus-cycles" "raw-cid-write-retired" "raw-dtlb-walk" "raw-cnt-cycles" "raw-crypto-spec" "raw-dmb-spec" "raw-dp-spec" "raw-dsb-spec" "raw-exc-dabort" "raw-exc-hvc" "raw-exc-irq" "raw-exc-pabort" "raw-exc-return" "raw-exc-svc" "raw-exc-taken" "raw-exc-trap-dabort" "raw-exc-trap-other" "raw-exc-undef" "raw-inst-retired" "raw-inst-spec" "raw-isb-spec" "raw-itlb-walk" "raw-l1d-cache" "raw-l1d-cache-refill" "raw-l1d-cache-inval" "raw-l1d-cache-rd" "raw-l1d-cache-refill-rd" "raw-l1d-cache-refill-inner" "raw-l1d-cache-refill-outer" "raw-l1d-cache-wb" "raw-l1d-cache-wb-clean" "raw-l1d-cache-wb-victim" "raw-l1d-cache-wr" "raw-l1d-cache-refill-wr" "raw-l1d-tlb" "raw-l1d-tlb-refill" "raw-l1d-tlb-rd" "raw-l1d-tlb-refill-rd" "raw-l1d-tlb-wr" "raw-l1d-tlb-refill-wr" "raw-l1i-cache" "raw-l1i-cache-refill" "raw-l1i-tlb" "raw-l1i-tlb-refill" "raw-l2d-cache" "raw-l2d-cache-refill" "raw-l2d-cache-allocate" "raw-l2d-cache-inval" "raw-l2d-cache-rd" "raw-l2d-cache-refill-rd" "raw-l2d-cache-wb" "raw-l2d-cache-wb-clean" "raw-l2d-cache-wb-victim" "raw-l2d-cache-wr" "raw-l2d-cache-refill-wr" "raw-l2d-tlb" "raw-l2d-tlb-refill" "raw-l2d-tlb-rd" "raw-l2d-tlb-refill-rd" "raw-l2d-tlb-wr" "raw-l2d-tlb-refill-wr" "raw-l3d-cache" "raw-l3d-cache-refill" "raw-l3d-cache-allocate" "raw-l3d-cache-rd" "raw-l3d-cache-refill-rd" "raw-ld-retired" "raw-ld-spec" "raw-ldrex-spec" "raw-ldst-spec" "raw-ll-cache-rd" "raw-ll-cache-miss-rd" "raw-mem-access" "raw-mem-access-rd" "raw-mem-access-wr" "raw-pc-write-retired" "raw-pc-write-spec" "raw-rc-ld-spec" "raw-rc-st-spec" "raw-st-retired" "raw-st-spec" "raw-stall-backend" "raw-stall-frontend" "raw-strex-fail-spec" "raw-strex-pass-spec" "raw-strex-spec" "raw-vfp-spec" "raw-sve-inst-retired" "raw-ttbr-write-retired" "raw-unaligned-ld-spec" "raw-unaligned-st-spec" "raw-unaligned-ldst-retired" "raw-unaligned-ldst-spec" "branch-store-misses" "branch-stores" "L1-dcache-store-misses" "L1-dcache-stores")
sleep 1
echo $i
m=$n+1
x=$m+1
#adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 0.25 |tee -a $action_app_name.txt;
#	  done
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.6 --use-devfreq-counters |tee -a S_AEX_XTS.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 8.5 --use-devfreq-counters |tee -a S_Text_Compression.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.9 --use-devfreq-counters |tee -a S_Image_Compression.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4 --use-devfreq-counters |tee -a S_Navigation.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.62 --use-devfreq-counters |tee -a S_HTML5.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.64 --use-devfreq-counters |tee -a S_SQLite.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.53 --use-devfreq-counters |tee -a S_PDF_Rendering.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.4 --use-devfreq-counters |tee -a S_Text_Rendering.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.4 --use-devfreq-counters |tee -a S_Clang.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.92 --use-devfreq-counters |tee -a S_Camera.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 7.7 --use-devfreq-counters |tee -a S_N-Body_Physics.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.2 --use-devfreq-counters |tee -a S_Rigid_Body_Physics.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 6.3 --use-devfreq-counters |tee -a S_Gaussian_Blur.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.9 --use-devfreq-counters |tee -a S_Face_Detection.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 3.6 --use-devfreq-counters |tee -a S_Horizon_Detection.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2 --use-devfreq-counters |tee -a S_Image_Inpainting.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4.4 --use-devfreq-counters |tee -a S_HDR.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.95 --use-devfreq-counters |tee -a S_Ray_Tracing.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 7.5 --use-devfreq-counters |tee -a S_Structure_from_Motion.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4.7 --use-devfreq-counters |tee -a S_Speech_Recognition.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.4 --use-devfreq-counters |tee -a S_Machine_Learning.txt;

adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.1 --use-devfreq-counters |tee -a M_AEX_XTS.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 15.4 --use-devfreq-counters |tee -a M_Text_Compression.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4.8 --use-devfreq-counters |tee -a M_Image_Compression.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 8 --use-devfreq-counters |tee -a M_Navigation.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.3 --use-devfreq-counters |tee -a M_HTML5.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.6 --use-devfreq-counters |tee -a M_SQLite.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4.12 --use-devfreq-counters |tee -a M_PDF_Rendering.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 1.52 --use-devfreq-counters |tee -a M_Text_Rendering.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 4.4 --use-devfreq-counters |tee -a M_Clang.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 3.4 --use-devfreq-counters |tee -a M_Camera.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.82 --use-devfreq-counters |tee -a M_N-Body_Physics.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 3.5 --use-devfreq-counters |tee -a M_Rigid_Body_Physics.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 3.3 --use-devfreq-counters |tee -a M_Gaussian_Blur.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.75 --use-devfreq-counters |tee -a M_Face_Detection.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 5.75 --use-devfreq-counters |tee -a M_Horizon_Detection.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 3.85 --use-devfreq-counters |tee -a M_Image_Inpainting.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 8.55 --use-devfreq-counters |tee -a M_HDR.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2.3 --use-devfreq-counters |tee -a M_Ray_Tracing.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 17.4 --use-devfreq-counters |tee -a M_Structure_from_Motion.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 14.2 --use-devfreq-counters |tee -a M_Speech_Recognition.txt;
adb shell /data/local/tmp/./simpleperf stat -p $pid_name -e instructions,cpu-cycles,${things_list[n]},${things_list[m]},${things_list[x]}  --duration 2 --use-devfreq-counters |tee -a M_Machine_Learning.txt;
echo "over collection"
echo ${things_list[n]}
